# Generated by Django 4.1.5 on 2023-01-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbcoins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='ycoin',
            field=models.DateField(null=True),
        ),
    ]
